-- ==========================================
-- DB名 : Movie
-- O-HARAFILM テーブル定義
-- ==========================================


-- ==========================================
-- 子 → 親 の順に削除（再実行用）
-- ==========================================

DROP TABLE IF EXISTS INQUIRY_REPLIES;
DROP TABLE IF EXISTS RESERVATION_TICKETS;
DROP TABLE IF EXISTS RESERVATION_SEATS;
DROP TABLE IF EXISTS RESERVATIONS;
DROP TABLE IF EXISTS SCREENING_SCHEDULES;
DROP TABLE IF EXISTS INQUIRIES;
DROP TABLE IF EXISTS MOVIES;
DROP TABLE IF EXISTS ADMINS;



-- ==========================================
-- 1. 管理者
-- ==========================================

CREATE TABLE ADMINS (

    ADMIN_ID INT NOT NULL,

    -- ハッシュ化したパスワードを保存
    PASSWORD VARCHAR(255) NOT NULL,

    PRIMARY KEY (ADMIN_ID)
);



-- ==========================================
-- 2. 映画
-- ==========================================

CREATE TABLE MOVIES (

    MOVIE_ID
        INT
        GENERATED BY DEFAULT AS IDENTITY,

    TITLE
        VARCHAR(100)
        NOT NULL,

    -- 上映時間（分）
    DURATION
        INT
        NOT NULL,

    RELEASE_START_DATE
        DATE
        NOT NULL,

    RELEASE_END_DATE
        DATE
        NOT NULL,

    GENRE
        VARCHAR(50)
        NOT NULL,

    AGE_LIMIT
        VARCHAR(10)
        NOT NULL,

    DESCRIPTION
        CLOB
        NOT NULL,

    DIRECTOR
        VARCHAR(100)
        NOT NULL,

    -- CASTは予約語になる可能性があるため引用符を使用
    "CAST"
        VARCHAR(500)
        NOT NULL,

    POSTER_URL
        VARCHAR(500)
        NOT NULL,

    PRIMARY KEY (MOVIE_ID)
);



-- ==========================================
-- 3. 上映スケジュール
-- ==========================================

CREATE TABLE SCREENING_SCHEDULES (

    SCHEDULE_ID
        INT
        GENERATED BY DEFAULT AS IDENTITY,

    MOVIE_ID
        INT
        NOT NULL,

    SCREEN_NO
        INT
        NOT NULL,

    START_DATETIME
        TIMESTAMP
        NOT NULL,

    END_DATETIME
        TIMESTAMP
        NOT NULL,

    -- 2D / 3D / IMAXなど
    SCREENING_FORMAT
        VARCHAR(20)
        NOT NULL,

    PRIMARY KEY (SCHEDULE_ID),

    CONSTRAINT FK_SCHEDULE_MOVIE
        FOREIGN KEY (MOVIE_ID)
        REFERENCES MOVIES (MOVIE_ID)
);



-- ==========================================
-- 4. 予約
-- ==========================================

CREATE TABLE RESERVATIONS (

    RESERVATION_ID
        INT
        GENERATED BY DEFAULT AS IDENTITY,

    SCHEDULE_ID
        INT
        NOT NULL,


    -- ==========================
    -- お客様情報
    -- ==========================

    CUSTOMER_NAME
        VARCHAR(100)
        NOT NULL,

    CUSTOMER_KANA
        VARCHAR(100)
        NOT NULL,

    EMAIL
        VARCHAR(255)
        NOT NULL,

    PHONE
        VARCHAR(20)
        NOT NULL,


    -- ==========================
    -- 支払い情報
    -- ==========================

    -- counter / card など
    PAYMENT_METHOD
        VARCHAR(20)
        NOT NULL,

    TOTAL_PRICE
        INT
        NOT NULL,


    -- ==========================
    -- 予約状態
    -- ==========================

    RESERVED_AT
        TIMESTAMP
        NOT NULL,

    STATUS
        VARCHAR(20)
        DEFAULT '予約済み'
        NOT NULL,


    PRIMARY KEY (RESERVATION_ID),


    CONSTRAINT FK_RESERVATION_SCHEDULE
        FOREIGN KEY (SCHEDULE_ID)
        REFERENCES SCREENING_SCHEDULES (SCHEDULE_ID),


    -- RESERVATION_SEATSから
    -- RESERVATION_ID + SCHEDULE_ID を参照するため
    CONSTRAINT UQ_RESERVATION_SCHEDULE
        UNIQUE (RESERVATION_ID, SCHEDULE_ID)
);



-- ==========================================
-- 5. 予約座席
-- ==========================================

CREATE TABLE RESERVATION_SEATS (

    RESERVATION_SEAT_ID
        INT
        GENERATED BY DEFAULT AS IDENTITY,

    RESERVATION_ID
        INT
        NOT NULL,

    SCHEDULE_ID
        INT
        NOT NULL,

    -- A1 / A2 / B3など
    SEAT_NO
        VARCHAR(10)
        NOT NULL,


    PRIMARY KEY (RESERVATION_SEAT_ID),


    -- 予約と上映スケジュールの組み合わせを保証
    CONSTRAINT FK_SEAT_RESERVATION
        FOREIGN KEY (
            RESERVATION_ID,
            SCHEDULE_ID
        )
        REFERENCES RESERVATIONS (
            RESERVATION_ID,
            SCHEDULE_ID
        ),


    -- 同じ上映回で同じ座席を予約できないようにする
    CONSTRAINT UQ_SEAT_PER_SCHEDULE
        UNIQUE (
            SCHEDULE_ID,
            SEAT_NO
        )
);



-- ==========================================
-- 6. 予約券種
-- ==========================================

CREATE TABLE RESERVATION_TICKETS (

    RESERVATION_TICKET_ID
        INT
        GENERATED BY DEFAULT AS IDENTITY,

    RESERVATION_ID
        INT
        NOT NULL,

    -- 一般 / 学生 / シニアなど
    TICKET_TYPE
        VARCHAR(20)
        NOT NULL,

    -- 枚数
    QUANTITY
        INT
        NOT NULL,

    -- 予約時点での1枚の価格
    UNIT_PRICE
        INT
        NOT NULL,


    PRIMARY KEY (RESERVATION_TICKET_ID),


    CONSTRAINT FK_TICKET_RESERVATION
        FOREIGN KEY (RESERVATION_ID)
        REFERENCES RESERVATIONS (RESERVATION_ID)
);



-- ==========================================
-- 7. お問い合わせ
-- ==========================================

CREATE TABLE INQUIRIES (

    INQUIRY_ID
        INT
        GENERATED BY DEFAULT AS IDENTITY,

    NAME
        VARCHAR(50)
        NOT NULL,

    EMAIL
        VARCHAR(255)
        NOT NULL,

    SUBJECT
        VARCHAR(100)
        NOT NULL,

    BODY
        CLOB
        NOT NULL,

    SENT_AT
        TIMESTAMP
        NOT NULL,

    STATUS
        VARCHAR(20)
        DEFAULT '未対応'
        NOT NULL,


    PRIMARY KEY (INQUIRY_ID)
);



-- ==========================================
-- 8. お問い合わせ返信
-- ==========================================

CREATE TABLE INQUIRY_REPLIES (

    REPLY_ID
        INT
        GENERATED BY DEFAULT AS IDENTITY,

    INQUIRY_ID
        INT
        NOT NULL,

    REPLY_BODY
        CLOB
        NOT NULL,

    STAFF_NAME
        VARCHAR(50)
        NOT NULL,

    REPLIED_AT
        TIMESTAMP
        NOT NULL,


    PRIMARY KEY (REPLY_ID),


    CONSTRAINT FK_REPLY_INQUIRY
        FOREIGN KEY (INQUIRY_ID)
        REFERENCES INQUIRIES (INQUIRY_ID)
);